### ISSUE TITLE
Create a mastodon identity

### ISSUE THREAD

**Issue by anadahz** [PrivacyLx/privacylx-issue-tracker#10]
This task is about creating a mastodon identity.

**Comment by francisco-core** [comment]
Luna is working on this. We need to choose the server in which it will be. The privacytools.io mastodon sounds like a viable option

**Comment by francisco-core** [comment]
I think this is done. I'll ask her for the handle

**Comment by anadahz** [comment]
Is this implemented?

**Comment by anadahz** [comment]
Implemented: https://social.privacytools.io/@PrivacyLX
