### ISSUE TITLE
Create a matrix room

### ISSUE THREAD

**Issue by anadahz** [PrivacyLx/privacylx-issue-tracker#12]
This task is about creating a matrix room for PrivacyLx.
Ideally it should bridge with other channels such as #privacylx on IRC.

**Comment by francisco-core** [comment]
to read: https://gist.github.com/maxidorius/5736fd09c9194b7a6dc03b6b8d7220d0
Haven't yet taken the time. But it sounds serious. Rocket.chat might be a better alternative

**Comment by anadahz** [comment]
> to read: https://gist.github.com/maxidorius/5736fd09c9194b7a6dc03b6b8d7220d0
Can you please summarize or point the parts that are relevant to us?

I prefer matrix for its decentralization features.

Some relevant discussion can be read here: https://lists.ghserv.net/pipermail/lt/2019-June/017816.html

**Comment by francisco-core** [comment]
This has now been done: https://riot.im/app/#/room/#privacylx:matrix.org

Thanks @anadahz

**Comment by anadahz** [comment]
Great, closing this issue.
