### ISSUE TITLE
Fix English index.html page

### ISSUE THREAD

**Issue by kcg295** [PrivacyLx/privacylx-issue-tracker#14]
Currently, information about the organization, its beliefs, and its goals are in Portuguese, even if one goes to the English page. These sections should be translated into English.

**Comment by francisco-core** [comment]
The description is now translated, thanks to @kcg295.
But the translation for the next even is still in portuguese only

**Comment by francisco-core** [comment]
My mistake, it is already correct. It's just that one of the events's title and summary were not translated
