### ISSUE TITLE
Add v2 and v3 onion URLs on the website

### ISSUE THREAD

**Issue by anadahz** [PrivacyLx/privacylx-issue-tracker#2]
The onion links should be added to the website.
We can add a line on the bottom of the website similar to:
`Tor Onion Service v2 | Tor Onion Service v3` or present it in any other way.

**Comment by anadahz** [comment]
Done in https://github.com/PrivacyLx/website/pull/5 .

**Comment by kcg295** [comment]
There seems to be a small issue with this. When clicking language links on the bottom of the page, it brings us out of the onion site and back into the regular privacylx website.

**Comment by anadahz** [comment]
This is not related only to the onion addresses but also on `https://privacylx.org`.
I'm going to open a separate ticket for this (#20), thanks for reporting it.
