### ISSUE TITLE
@privacylx.org email accounts

### ISSUE THREAD

**Issue by francisco-core** [PrivacyLx/privacylx-issue-tracker#22]
Please, set this up only when you have the time.

**Comment by francisco-core** [comment]
probably the same as #13

**Comment by kcg295** [comment]
This can be closed now, no?

**Comment by francisco-core** [comment]
Yup

Activado qua, mai 15, 2019 às 17:11, Kevin <notifications@github.com> escreveu:

**Comment by francisco-core** [comment]
Yup. Please go ahead

Activado qua, mai 15, 2019 às 17:11, Kevin <notifications@github.com> escreveu:
