### ISSUE TITLE
Populate all DNS records required for the mail server

### ISSUE THREAD

**Issue by anadahz** [PrivacyLx/privacylx-issue-tracker#23]
This ticket is about setting up all the DNS records for privacylx.org mail server (mail.privacylx.org).

Related Mailcow documentation: [DNS Setup](https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-dns/)

**Comment by francisco-core** [comment]
Is this still not fixed? I think the link is broken @anadahz. Do you mean the DKIM and other stuff?
I've successfully used the mailserver to send messages to a gmail. If it works for that, it should work for anything else

**Comment by anadahz** [comment]
Updated https://github.com/PrivacyLx/privacylx-issue-tracker/issues/23#issue-433411575 with the correct link. I haven't added all DNS entries and for sure some entries are missing that includes also DKIM and DMARC.

> I've successfully used the mailserver to send messages to a gmail. If it works for that, it should work for anything else

Email servers are a very complex service, we should take care of the DNS entries, especially DKIM and DMARC to ensure that the email are not ending up as spam.

**Comment by francisco-core** [comment]
> Email server are a very complex service, we should take care of the DNS entries, especially DKIM and DMARC to ensure that the email are not ending up as spam.

For sure it is. I don’t know much about anti-spam configurations for email.

I got today someone mesaging me about it ending up in spam.

Is there a role for dns configuation for this that we can use. If not, do you want to look into any specific dns entry?

Activado ter, jun 25, 2019 às 19:06, anadahz <notifications@github.com> escreveu:

**Comment by anadahz** [comment]
> Is there a role for dns configuation for this that we can use. If not, do you want to look into any specific dns entry?

Most probably not but perhaps there is an API that can help to build a role, until then manually modifying the DNS entries will be the best option.

**Comment by anadahz** [comment]
This is done --waiting for the PTR record to propagate.

I created a [script](https://github.com/PrivacyLx/devops/blob/master/scripts/mailserver-dns-check) that queries all DNS entries used by mailcow. 
It eases checking of the correct DNS entries.
