### ISSUE TITLE
Add www subdomain to website

### ISSUE THREAD

**Issue by anadahz** [PrivacyLx/privacylx-issue-tracker#24]
This issue is about adding the appropriate DNS record(s) so that the subdomain www points to Privacylx's [website](https://privacylx.org).

**Comment by francisco-core** [comment]
why is this needed? I saw in your deployment configs, but I don't get the why? Do some old computers not work well without it?

**Comment by anadahz** [comment]
Often people are using the subdomain `www` "by default" so one will not be able to access the website from this URL: https://www.privacylx.org

**Comment by anadahz** [comment]
I have set the DNS record once #3 is reviewed, merged and deployed the website will be reachable also on the `www` subdomain.

**Comment by francisco-core** [comment]
Perfect. But now we need to change the website deployment role to also receive requests from that, right?

Activado qui, jul 4, 2019 às 12:34, anadahz <notifications@github.com> escreveu:

**Comment by anadahz** [comment]
> Perfect. But now we need to change the website deployment role to also receive requests from that, right?

Correct, this happens here: https://github.com/PrivacyLx/devops/pull/3/files#diff-01789c88889a87f5ae690ad3a8e516d3R1

**Comment by anadahz** [comment]
Closing, this has been done in: https://github.com/PrivacyLx/devops/pull/3
