### ISSUE TITLE
Website's v3 onion service unreachable

### ISSUE THREAD

**Issue by anadahz** [PrivacyLx/privacylx-issue-tracker#25]
It seems that the v3 onion service of the website cannot be reached.

We should have a look at it.

**Comment by francisco-core** [comment]
I had a quick look at it and I think the problem might have to do with the fact that in the `torrc` the config for the onion v3 website is the line that mentions explicitly the version of the onion service:

```txt
HiddenServiceDir /var/lib/tor/privacylx-website-v3/
HiddenServicePort 80 127.0.0.1:80
```

But adding the line `HiddenServiceVersion 3` and reloading the tor systemd unit didn't seem to help.
But previously it was working, so I don't know what could have happened.

Also, the onion part of the deployments is done with this ansible role https://github.com/systemli/ansible-role-onion

**Comment by anadahz** [comment]
> But previously it was working, so I don't know what could have happened.

Do you any logs, or anything that could help us to examine the issue?

> Also, the onion part of the deployments is done with this ansible role https://github.com/systemli/ansible-role-onion

By using external roles means that we should always take care about the upstream changes to not mess up with our stuff. I prefer creating my own roles except there is a roles that works out of the box and does exactly what we want. I think that I have a role that creates onions somewhere let me know if you want me to look into it.

Please take care before testing new things that the website and all its endpoints are always up and running. You may use a staging server to find out if everything works fine before you deploy live.
