### ISSUE TITLE
Devops caddy not reloading systemd unit

### ISSUE THREAD

**Issue by francisco-core** [PrivacyLx/privacylx-issue-tracker#26]
The `caddy-website` role over in https://github.com/PrivacyLx/devops is not reloading upon being notified. It has to be manually reloaded from the terminal with `systemctl restart caddy`.

Investigate what that is not working

**Comment by anadahz** [comment]
> The caddy-website role over in https://github.com/PrivacyLx/devops is not reloading upon being 
notified.

Do you see an error message or anything that shows caddy service not being reloaded upon modification?

Some guesses:
1. This [part of the code]( https://github.com/PrivacyLx/devops/blob/c70ff8c66b1b66763f8f11c83e92a3b63dc766b3/ansible/roles/caddy-website/tasks/build-website.yml#L77) where notify could act is commented out.

I tried find out what's wrong but I cannot get to run the [website role](https://github.com/PrivacyLx/devops/blob/master/ansible/deploy-website.yml). In case it's useful to you I get the following error:
```
TASK [caddy-website : Build hugo-0.54.0 docker image] **************************************************************************************************************************************************************
fatal: [privacylx.org]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (docker_image) module: build, source Supported parameters include: api_version, archive_path, buildargs, cacert_path, cert_path, container_limits, debug, docker_host, dockerfile, force, http_timeout, key_path, load_path, name, nocache, path, pull, push, repository, rm, ssl_version, state, tag, timeout, tls, tls_hostname, tls_verify, use_tls"}
```

We should aim to have working roles on master branch, while testing and WIP roles and projects should be better on a different branch or repository.

Feel free to send a pull request and ping me to review it.

**Comment by francisco-core** [comment]
> I tried find out what's wrong but I cannot get to run the [website role](https://github.com/PrivacyLx/devops/blob/master/ansible/deploy-website.yml). In case it's useful to you I get the following error:
> 
> ```
> TASK [caddy-website : Build hugo-0.54.0 docker image] **************************************************************************************************************************************************************
> fatal: [privacylx.org]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (docker_image) module: build, source Supported parameters include: api_version, archive_path, buildargs, cacert_path, cert_path, container_limits, debug, docker_host, dockerfile, force, http_timeout, key_path, load_path, name, nocache, path, pull, push, repository, rm, ssl_version, state, tag, timeout, tls, tls_hostname, tls_verify, use_tls"}
> ```

That has to do with an outdated ansible version. According to [the docs](https://docs.ansible.com/ansible/latest/modules/docker_image_module.html), to use the `build` parameter for the ansible module we need at least ansible version 2.8

**Comment by francisco-core** [comment]
> This part of the code where notify could act is commented out.

I totally missed that. I think that might be what's missing.Thanks
