### ISSUE TITLE
Vacation error

### ISSUE THREAD

**Issue by mcattell78** [PrivacyLx/privacylx-issue-tracker#35]
Hi
We use Gridhost to access roundcude, but the vacation settings has started to display an error, every time we click on vacation. We get the below error:

"An error occoured - Error during connection"

This happens on every email account with Gridhost.

We have spoken to Gridhost, and they say its a Roundcude issue!

Can you please confirm if this is a Roundcube issue or Gridhost?

Thank you for any help!

**Comment by anadahz** [comment]
This is an invalid issue, closing.
