### ISSUE TITLE
Create a welcome pack for new members

### ISSUE THREAD

**Issue by francisco-core** [PrivacyLx/privacylx-issue-tracker#37]
We need to create a pack for welcoming people to the organization, which should contain:
- it's mission
- the structure of the organization
- what people can do to help
- Other stuff???

**Comment by francisco-core** [comment]
done. https://cafe.privacylx.org/t/draft-create-a-welcome-pack/154

**Comment by anadahz** [comment]
This is implemented: https://privacylx.org/community/welcome-pack/
