### ISSUE TITLE
Adjust Discourse theme constrast

### ISSUE THREAD

**Issue by anadahz** [PrivacyLx/privacylx-issue-tracker#38]
The dark theme of [cafe.privacylx.org](https://cafe.privacylx.org) is not always readable by anyone and on all weather and light conditions. A theme with more contrast can improve readability for users with bad vision, on low quality monitors and reading on smaller screens and bad lighting.

I suggest to add an option for a user to switch to a brighter higher contrast theme version via a day/night button. An example with screenshots taken from [android-x86 website](https://www.android-x86.org/):

![Night](https://user-images.githubusercontent.com/4969544/62543876-42409780-b84e-11e9-8052-38e3dcbb5798.png)
------------------------------------------------
![Day](https://user-images.githubusercontent.com/4969544/62543877-42409780-b84e-11e9-8452-05f246980971.png)

**Comment by francisco-core** [comment]
# (New) White theme
There are some people that do prefer a white theme, which is understandable. So here it is!

![theme-white](https://user-images.githubusercontent.com/32313429/65072414-61b7fd80-d980-11e9-9dd7-316c45be8652.png)

## How to change to the white version
On the hamburger menu up at the top there is now an option to select the theme

![theme-selection](https://user-images.githubusercontent.com/32313429/65072443-71cfdd00-d980-11e9-93cb-9bcbb2d80ae2.png)

This was done though a theme component for discourse: https://meta.discourse.org/t/hamburger-theme-selector/61210

**Comment by anadahz** [comment]
Great, thank you for implementing this!
