### ISSUE TITLE
Add more RAM to the testing server

### ISSUE THREAD

**Issue by anadahz** [PrivacyLx/privacylx-issue-tracker#63]
This issue is about adding a testing server with sufficient RAM to run all services.

**Comment by anadahz** [comment]
@francisco-core I added 2 more Gig of RAM and 1 extra CPU core on the testing server. Does this suffices?

**Comment by francisco-core** [comment]
I think the ram is enough. Could just add 5 more GB to disk

```bash
user@f-test:/var/discourse# ./launcher rebuild app
You have less than 5GB of free space on the disk where /var/lib/docker is located. You will need more space to continue
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1       10G  7.5G  2.6G  75% /
```

**Comment by anadahz** [comment]
It's not so easy to add more disk space to the VM, try to remove old images and containers that are no longer required.

**Comment by anadahz** [comment]
It will be easier to re-create the VM if you need more disk space.

**Comment by francisco-core** [comment]
Yup. Cleaning the other images solves it. Thanks!

**Comment by francisco-core** [comment]
It's pretty tight though. But we can close this for now

**Comment by anadahz** [comment]
Feel free to open a new issue if/when you need a test server with greater disk capacity.

**Comment by francisco-core** [comment]
Will do. For now it's fine thanks
