### ISSUE TITLE
Add about/contact us page 

### ISSUE THREAD

**Issue by anadahz** [PrivacyLx/privacylx-issue-tracker#7]
Add an about/contact page with communication channel such as email, IRC, mastodon, XMPP or other.
- [x] IRC (OFTC channel: #privacylx)
- [x] Email(s) #13
- [x] Mastodon #10
- [ ] XMPP #11
- [x] Matrix #12

**Comment by anadahz** [comment]
I updated the issue to break tasks in separate tickets.

**Comment by kcg295** [comment]
I think the e-mail issue is complete now, no? We can check that off.

**Comment by anadahz** [comment]
> I think the e-mail issue is complete now, no? We can check that off.

@kcg295 We still miss the main contact email address of the website.

**Comment by francisco-core** [comment]
Since we are now an association, we should add also the "Estatutos" here

**Comment by anadahz** [comment]
> Since we are now an association, we should add also the "Estatutos" here

Added an issue about it here: https://github.com/PrivacyLx/privacylx-issue-tracker/issues/34

**Comment by francisco-core** [comment]
@kcg295 will finish this by tomorrow noon

**Comment by kcg295** [comment]
I have a draft written but I will need bios. I'll reach out on the forum and ask people to send bios to my email to add.

**Comment by kcg295** [comment]
Also this will need Portuguese translation. I wrote it in English. I can try to handle some of that, if any native Portuguese speaker wants to help with it.

**Comment by francisco-core** [comment]
https://github.com/PrivacyLx/website/pull/53 makes way for this. There is now an `/about` category.

**Comment by anadahz** [comment]
https://github.com/PrivacyLx/website/pull/53 is merged closing issue.
