### ISSUE TITLE
BBB: "create room" button not available after 4 rooms created

### ISSUE THREAD

**Issue by git-alm** [PrivacyLx/privacylx-issue-tracker#84]
Hi!

After creating 4 meeting rooms (other than Home Room), the "create room" button is no longer available. This may be due to a set limit to the number of rooms which can be created by any user on the server. Could this limit be increased?

Thanks!

**Comment by anadahz** [comment]
We have now changed the limit of rooms a user can have (including Home Room) to `10`.
Hope this works for you.
