### ISSUE TITLE
Remove Third-party scripts from website

### ISSUE THREAD

**Issue by francisco-core** [PrivacyLx/privacylx-issue-tracker#9]
on the file `website/themes/hugo-bootstrap/layouts/_default/baseof.html` some third-party scripts are called. We should host our own copy of these

**Comment by kcg295** [comment]
Are the scripts 100% necessary? Ideally we should be compatable with browsers that choose to block all JS.

**Comment by anadahz** [comment]
According to the comment in [baseof.html](https://github.com/PrivacyLx/website/blob/master/themes/hugo-bootstrap/layouts/_default/baseof.html#L44) seems there are optional.

A safe move would be to test that the website is working fine without them.

**Comment by francisco-core** [comment]
I tested removing them before. Most of the website works fine. It's just that on mobile the navigation bar does not drop down. We could host those locally I guess. Ideally no script would be needed. But that would need to rethink the header of the page and maybe do one of those dynamic things with bootstrap "@media", I think to adapt to the screen-size. But I'm not too familiar with that.

**Comment by anadahz** [comment]
It seems that it's possible to use bootstrap [without jquery](http://daniemon.com/blog/bootstrap-without-jquery/).

**Comment by francisco-core** [comment]
The only problem left I think is the hamburger menu (for mobile versions). It doesn't seem to work without js. managed to remove popper.js which apparently was useless.
Someone was able to make a css-only version of the hamburger menu here: https://viralpatel.net/blogs/bootstrap-navbar-menu-without-javascript/. I was playing around with it but didn't manage to put it to work in the time I had available

**Comment by francisco-core** [comment]
closed by ["added header for mobile & removed scripts #8"](https://github.com/PrivacyLx/website/pull/8)
