### ISSUE TITLE
Upgrade BBB to ubuntu 18.04 (when available)

### ISSUE THREAD

**Issue by francisco-core** [PrivacyLx/privacylx-issue-tracker#97]
(emphasis mine; taken from [here](https://ubuntu.com/16-04))

> Ubuntu 16.04 LTS is supported until 2024 through Canonical’s Extended Security Maintenance (ESM) product. Xenial enters the ESM period in **April 2021**, with security patches provided for an additional three years beyond the traditional five-year standard support.

Related BBB issue: https://github.com/bigbluebutton/bigbluebutton/issues/8474#issuecomment-802798671

**Comment by anadahz** [comment]
Yes, once BBB is available for 18.04, we should update to a new Ubuntu version ASAP.

**Comment by anadahz** [comment]
Implemented in: PrivacyLx/devops@f807890
