### ISSUE TITLE
Update BigBlueButton default slide to reflect the newer version

### ISSUE THREAD

**Issue by anadahz** [PrivacyLx/privacylx-issue-tracker#99]
This issue is about updating the BigBlueButton default slide to the newer version.
Bonus: Add an empty slide should be added at the end (only with the PrivacyLx logo) for free-form painting :)

The default slides are located here: https://github.com/PrivacyLx/devops/blob/master/ansible/roles/bigbluebutton/files/default.pdf

**Comment by francisco-core** [comment]
We stopped supporting BigBlueButton
